language: android

# Run on new travis infrastructure
sudo: false

# Don't check out submodules for faster builds with less dependencies
git:
  submodules: false

env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a

android:
  components:
    # Use the latest platform tools
    - platform-tools
    - tools

    # Use the desired build tools
    - build-tools-23.0.3

    # Project target SDK
    - android-23

    # Project extra configuration
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew assemble lint test connectedAndroidTest